/**
 * Represents a single file or directory node within the native file system.
 * This structure is generated by the Rust backend and consumed by the React File Explorer.
 */
export interface FileNode {
    name: string;
    path: string;
    is_directory: boolean;
    children?: FileNode[];
    extension?: string;
    size_bytes?: number;
    last_modified_timestamp?: number;
}