import { FileOpsIPC } from '@services/rust-bridge/fileOpsIpc';
import { LinterCard } from '@core/contracts/WardenSchema';
import { SystemLogger, LogLevel } from './systemLogger';

/**
 * Isolated memory buffer for capturing Mock Engine stress tests.
 * Formats AI payloads and Heuristic Engine responses into chronological Markdown.
 * Exports strictly to disk upon manual user request to prevent I/O throttling.
 */
export class DiagnosticLogger {
    private static buffer: string[] = [];

    /**
     * Initializes a new chronological block for an AI generation event.
     */
    public static logSessionStart(prompt: string): void {
        const timestamp = new Date().toISOString();
        this.buffer.push(`\n## [${timestamp}] AI Generation Session`);
        this.buffer.push(`**Prompt:** "${prompt}"\n`);
    }

    /**
     * Captures the completed payload exactly as it was streamed to the editor.
     */
    public static logGeneratedCode(code: string): void {
        this.buffer.push(`### AI Payload\n\`\`\`typescript\n${code}\n\`\`\`\n`);
    }

    /**
     * Captures the resulting diagnostic cards generated by the Rust backend.
     */
    public static logWardenFindings(cards: LinterCard[]): void {
        this.buffer.push(`### Warden Engine Analysis`);
        
        // Strict boundary validation to prevent mapping errors
        const safeCards = Array.isArray(cards) ? cards : [];
        
        if (safeCards.length === 0) {
            this.buffer.push(`*✅ No issues detected. (Ghost Pass)*\n`);
        } else {
            this.buffer.push(`*⚠️ Caught ${safeCards.length} issues:*`);
            safeCards.forEach(card => {
                this.buffer.push(`- **[${card.level}]** \`${card.rule_triggered}\` (Lines ${card.line_start}-${card.line_end}): ${card.message}`);
            });
            this.buffer.push(`\n`);
        }
        
        this.buffer.push(`---`);
    }

    /**
     * Dumps the internal memory buffer to the active workspace root via Rust IPC.
     */
    public static async exportLog(workspacePath: string | null): Promise<void> {
        if (!workspacePath) {
            SystemLogger.log(LogLevel.WARN, 'DiagnosticLogger', 'Cannot export log: No active workspace directory.');
            return;
        }

        if (this.buffer.length === 0) {
            SystemLogger.log(LogLevel.INFO, 'DiagnosticLogger', 'Diagnostic buffer is empty. Nothing to export.');
            return;
        }

        // Normalize slashes to ensure cross-platform compatibility for the file path
        const normalizedPath = `${workspacePath}/warden_diagnostic_log.md`.replace(/\\/g, '/');
        const header = `# Warden IDE Diagnostic Log\n*Automated capture of AI generation payloads and Heuristic Engine responses.*\n\n`;
        const content = header + this.buffer.join('\n');

        try {
            await FileOpsIPC.writeFile(normalizedPath, content);
            SystemLogger.log(LogLevel.INFO, 'DiagnosticLogger', `Diagnostic log safely exported to ${normalizedPath}`);
        } catch (error) {
            SystemLogger.log(LogLevel.ERROR, 'DiagnosticLogger', 'Failed to write diagnostic log to disk.', error);
        }
    }
}