use tree_sitter::{Parser, Query, QueryCursor};
use std::sync::Arc;
use crate::warden_engine::dependency_map::DependencyMap;
use super::LinterCard;
use super::rules::ErrorLevel;

/**
 * Structural analyzer utilizing Tree-sitter to catch hallucinated code and syntax errors.
 */
pub struct AstAnalyzer {}

impl AstAnalyzer {
    pub fn new() -> Self {
        Self {}
    }

    /**
     * Executes strict structural validation against the AI payload.
     */
    pub fn detect_hallucinations(
        &self,
        file_extension: &str,
        full_file_content: &str,
        start_line: usize,
        end_line: usize,
        dependency_map: &Arc<DependencyMap>
    ) -> Vec<LinterCard> {
        let mut cards = Vec::new();
        let mut parser = Parser::new();

        let language = match file_extension {
            "ts" | "tsx" => tree_sitter_typescript::language_typescript(),
            "js" | "jsx" => tree_sitter_javascript::language(),
            _ => return cards, 
        };

        parser.set_language(language).expect("Error loading grammar");
        let tree = parser.parse(full_file_content, None).expect("AST parsing failed");

        // QUERY 1: Syntax Errors (Fragment Detection)
        // Catches native (ERROR) nodes generated by cut-off or broken code streams.
        let error_query = Query::new(language, "(ERROR) @error").expect("Invalid ERROR query");
        let mut cursor = QueryCursor::new();
        let matches = cursor.matches(&error_query, tree.root_node(), full_file_content.as_bytes());

        for m in matches {
            for capture in m.captures {
                let node = capture.node;
                let node_line = node.start_position().row + 1;

                if node_line >= start_line && node_line <= end_line {
                    cards.push(LinterCard {
                        id: format!("WDN-FRAG-{}-{}", node_line, node.start_position().column),
                        level: ErrorLevel::Warning,
                        line_start: node_line,
                        line_end: node_line,
                        message: "Incomplete syntax detected. AI generation may have been truncated or broken.".to_string(),
                        rule_triggered: "WDN-AST-FRAG".to_string(),
                        suggested_fix: Some("Request the AI to continue the code block or fix the broken syntax.".to_string()),
                    });
                }
            }
        }

        // QUERY 2: Hallucination Detection (Classes and Member Expressions)
        let hall_query = Query::new(
            language,
            r#"
            (new_expression constructor: (identifier) @target)
            (call_expression function: (member_expression object: (identifier) @target property: (property_identifier)))
            "#
        ).expect("Invalid Hallucination query");

        let mut hall_cursor = QueryCursor::new();
        let hall_matches = hall_cursor.matches(&hall_query, tree.root_node(), full_file_content.as_bytes());

        for m in hall_matches {
            for capture in m.captures {
                let node = capture.node;
                let node_line = node.start_position().row + 1;

                if node_line >= start_line && node_line <= end_line {
                    if let Ok(symbol_name) = node.utf8_text(full_file_content.as_bytes()) {
                        
                        // Strict capitalization heuristic: We only cross-reference Custom Types/Classes
                        if let Some(first_char) = symbol_name.chars().next() {
                            if first_char.is_uppercase() && !dependency_map.symbol_exists(symbol_name) {
                                cards.push(LinterCard {
                                    id: format!("WDN-MOCK-{}-{}", node_line, symbol_name),
                                    level: ErrorLevel::Critical,
                                    line_start: node_line,
                                    line_end: node_line,
                                    message: format!("Hallucinated Dependency: '{}' does not exist in the project architecture.", symbol_name),
                                    rule_triggered: "WDN-MOCK-001".to_string(),
                                    suggested_fix: Some("Provide the AI with the correct class file, or prompt it to implement this dependency.".to_string()),
                                });
                            }
                        }
                    }
                }
            }
        }

        cards
    }
}