use tree_sitter::{Query, QueryCursor};
use crate::warden_engine::utils::get_parser_and_language;
use crate::warden_engine::dependency_map::DependencyMap;
use super::LinterCard;
use super::rules::ErrorLevel;
use std::sync::Arc;

/**
 * Structural analyzer utilizing Tree-sitter to detect semantic technical debt 
 * and architectural hallucinations generated by the AI.
 */
pub struct AstAnalyzer {}

impl AstAnalyzer {
    pub fn new() -> Self {
        Self {}
    }

    /**
     * Traverses the Abstract Syntax Tree of the provided buffer.
     * Extracts function/class invocations specifically within the targeted payload range
     * and validates their existence against the global project cache.
     */
    pub fn detect_hallucinations(
        &self,
        file_extension: &str,
        full_file_content: &str,
        start_line: usize,
        end_line: usize,
        dependency_map: &Arc<DependencyMap>,
    ) -> Vec<LinterCard> {
        let mut cards = Vec::new();
        
        let (mut parser, language) = match get_parser_and_language(file_extension) {
            Ok(p) => p,
            Err(_) => return cards,
        };

        let tree = match parser.parse(full_file_content, None) {
            Some(t) => t,
            None => return cards,
        };

        let query_str = if file_extension == "ts" || file_extension == "tsx" || file_extension == "js" {
            r#"
                (call_expression function: (identifier) @func_call)
                (call_expression function: (member_expression property: (property_identifier) @method_call))
                (new_expression constructor: (identifier) @class_instantiation)
            "#
        } else {
            r#"
                (call_expression function: (identifier) @func_call)
                (call_expression function: (field_expression field: (field_identifier) @method_call))
                (call_expression function: (scoped_identifier name: (identifier) @scoped_call))
            "#
        };

        let query = match Query::new(language, query_str) {
            Ok(q) => q,
            Err(_) => return cards,
        };

        let mut cursor = QueryCursor::new();
        let source_bytes = full_file_content.as_bytes();

        let matches = cursor.matches(&query, tree.root_node(), source_bytes);

        for m in matches {
            for capture in m.captures {
                let node = capture.node;
                let line = node.start_position().row + 1;
                
                if line >= start_line && line <= end_line {
                    if let Ok(symbol) = std::str::from_utf8(&source_bytes[node.byte_range()]) {
                        
                        let is_custom_type = symbol.chars().next().map_or(false, |c| c.is_uppercase());
                        
                        if is_custom_type && !dependency_map.symbol_exists(symbol) {
                            cards.push(LinterCard {
                                // Generate a unique ID for the frontend Kanban board to snap to
                                id: format!("WDN-AST-MOCK-{}-{}", symbol, line),
                                level: ErrorLevel::Critical,
                                line_start: line,
                                line_end: line,
                                message: format!("Hallucinated Dependency: '{}' does not exist in the project architecture.", symbol),
                                rule_triggered: "WDN-MOCK-001".to_string(),
                                suggested_fix: Some("Ensure the class/struct actually exists in your project before attempting to invoke it.".to_string()),
                            });
                        }
                    }
                }
            }
        }

        cards
    }
}